### ISSUE TITLE
挂载javaagent时报错

### ISSUE THREAD

**Issue by G0m1b4ko** [chenlvtang/TinyRASP#1]
将Agent模块用maven打包成jar包供SpringVulTest模块挂载javaagent启动时报错。
报错如下：
![image](https://github.com/chenlvtang/TinyRASP/assets/70828391/cbe2ba96-4002-4b1e-b52f-a29ea14db80d)

打断点初步判断是ins.addTransformer添加转换器这一方法报错，不知道怎么解决好

**Comment by chenlvtang** [comment]
不好意思，现在才看到，大概是Java版本问题，可以提供一下你的JDK版本吗

**Comment by chenlvtang** [comment]
或者是Maven打包时，没有将javassit一同打包，建议使用maven shade打包：mvn clean package shade:shade

**Comment by G0m1b4ko** [comment]
JDK17.0.8环境下使用maven shade打包解决了，谢谢
